### ISSUE TITLE
Minor cosmetic fix

### ISSUE THREAD

**Issue by metonymic-smokey** [gophercises/transform#1]
@joncalhoun the Exercise Details section in the README contains the line "A user could then _selec_ the image..." with a minor error in the word 'select'.
I think that could be changed to 'select' as in "A user could then _select_ the image...".

Thanks!

**Comment by metonymic-smokey** [comment]
P.S.
@joncalhoun absolutely love gophercises! Thanks a lot for the course!

**Comment by joncalhoun** [comment]
Thanks!
